package com.instagram.mcp.mcp.tool;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Component;

import com.instagram.mcp.config.InstagramProperties.InstagramConfig;
import com.instagram.mcp.mcp.dto.InstagramListImagesMcpResponse;
import com.instagram.mcp.mcp.dto.InstagramPostMcpResponse;
import com.instagram.mcp.upload.InstagramUploadService;
import com.instagram.mcp.upload.InstagramUploadService.Result;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

// MCP-exposed tools for Instagram image management.
// Clients call listInstagramImages first, then postImageToInstagram with a
// filename from that list — the tool generates a caption (Spring AI),
// publishes via the Graph API, and moves the file to destination-folder.
@Component
@RequiredArgsConstructor
@Slf4j
public class InstagramMcpTools {

    private static final Set<String> SUPPORTED_EXTENSIONS = Set.of(".jpg", ".jpeg", ".png", ".gif", ".heic", ".heif");

    private final InstagramConfig instagramConfig;
    private final InstagramUploadService uploadService;

    @Tool(description = "List all image files (.jpg, .jpeg, .png, .gif, .heic, .heif) currently waiting in the configured source folder.")
    public InstagramListImagesMcpResponse listInstagramImages() {
        log.debug("listInstagramImages (MCP): folder={}", instagramConfig.sourceFolder());
        Path folder = Paths.get(instagramConfig.sourceFolder());
        if (!Files.isDirectory(folder)) {
            return new InstagramListImagesMcpResponse(instagramConfig.sourceFolder(), 0, List.of());
        }
        try (Stream<Path> stream = Files.list(folder)) {
            List<String> images = stream
                    .filter(Files::isRegularFile)
                    .map(p -> p.getFileName().toString())
                    .filter(name -> {
                        int dot = name.lastIndexOf('.');
                        return dot >= 0 && SUPPORTED_EXTENSIONS.contains(name.substring(dot).toLowerCase());
                    })
                    .sorted()
                    .toList();
            return new InstagramListImagesMcpResponse(instagramConfig.sourceFolder(), images.size(), images);
        } catch (IOException e) {
            log.warn("listInstagramImages: cannot list folder={}", instagramConfig.sourceFolder(), e);
            return new InstagramListImagesMcpResponse(instagramConfig.sourceFolder(), 0, List.of());
        }
    }

    @Tool(description = "Post an image from the source folder to Instagram. If caption is blank, a caption is generated by Spring AI from the image. On success the file is moved to the destination folder.")
    public InstagramPostMcpResponse postImageToInstagram(
            @ToolParam(description = "Filename of the image in the source folder, e.g. sunset.jpg.") String filename,
            @ToolParam(description = "Optional caption. Leave empty to auto-generate via Spring AI.") String caption) {
        log.debug("postImageToInstagram (MCP): filename={}", filename);

        if (filename == null || filename.isBlank()) {
            return new InstagramPostMcpResponse(false, null, filename, caption, "Filename must not be blank.");
        }
        if (filename.contains("..") || filename.contains("/") || filename.contains("\\")) {
            return new InstagramPostMcpResponse(false, null, filename, caption, "Invalid filename.");
        }

        Path imagePath = Paths.get(instagramConfig.sourceFolder()).resolve(filename).normalize();
        if (!Files.exists(imagePath) || !Files.isRegularFile(imagePath)) {
            return new InstagramPostMcpResponse(false, null, filename, caption,
                    "Image not found in source folder: " + filename + ". Use listInstagramImages to see available files.");
        }

        Result result = uploadService.uploadAndMove(imagePath, caption);
        return new InstagramPostMcpResponse(
                result.success(),
                result.mediaId(),
                result.filename(),
                result.caption(),
                result.error());
    }
}
